#!/usr/bin/env python3
"""Generate CHANGELOG.md sections from this repo's own commit history.

A version's story is already written -- in the subjects of the commits that
shipped it -- so nothing here composes prose. It walks the commit history of
`scripts/plugin-src/plugin.json` to find the commit that bumped the version
to VERSION (that commit, plus every commit back to the previous bump, is the
version's range), groups those commits' subjects by conventional-commit
type into named headings, and prepends the result to CHANGELOG.md.
Regenerating a *released* version (one with a boundary commit already in
history) is refused, not silently duplicated -- see issue #42.

In-flight support: when VERSION matches the version already sitting in the
working-tree manifest but no commit has bumped it there yet, the section
covers every commit since the previous release through HEAD, dated today.
That's what lets the two-commit release ritual (docs/publishing.md) generate
the section *before* the release commit exists -- the mechanical release
commit itself therefore never appears in its own section, by design.
Rerunning the in-flight version replaces its provisional section (more work
may have landed since); rerunning a released version still refuses.

Modes:
    make-changelog.py VERSION      prepend/refresh the VERSION section
    make-changelog.py --notes VER  print VERSION's existing section to stdout
                                    (for `gh release create --notes-file -`),
                                    or exit nonzero naming the missing section

Exit codes: 0 success; 1 a lookup, refusal, or write failed (message on
stderr names the actual problem, not a bare "failed").

Stdlib only, so the kit stays copy-in portable -- see build-plugin.py's
docstring for the same rule.
"""
import argparse
import datetime
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLUGIN_MANIFEST_REL = os.path.join("scripts", "plugin-src", "plugin.json")
CHANGELOG_PATH = os.path.join(ROOT, "CHANGELOG.md")

HEADER = (
    "# Changelog\n\n"
    "Generated by `scripts/make-changelog.py <version>` from the commit "
    "history of `scripts/plugin-src/plugin.json` -- each section covers "
    "every commit between one version-bump commit and the next. Entries "
    "are commit subjects grouped by conventional-commit type and linked to "
    "their commit; the script writes no prose of its own. Regenerate a "
    "section instead of hand-editing it.\n"
)

# The four types the spec names explicitly, in the order sections render.
# Anything else (refactor, style, test, or a subject with no conventional
# prefix at all) falls into the catch-all rather than being dropped -- every
# in-range commit belongs to its section (constitution C-4's non-goal is
# about commits outside the range, not about filtering by type).
_KNOWN_TYPES = {"feat": "Features", "fix": "Bug Fixes", "docs": "Documentation", "chore": "Chores"}
_GROUP_ORDER = ["Features", "Bug Fixes", "Documentation", "Chores", "Other"]

# Matches any conventional-commit prefix (known type or not, scoped or not,
# breaking-change "!" or not) so _classify can strip it uniformly -- a raw
# `type(scope):` must never survive into a rendered entry, even one that
# lands in the "Other" catch-all.
_TYPE_RE = re.compile(r"^(\w+)(?:\(([^)]*)\))?!?:\s*(.*)$")


class ChangelogError(Exception):
    """Raised for any lookup/refusal condition; str(e) is the full diagnostic."""


def _git(args):
    """Run a git command rooted at ROOT and return its stdout, raising
    ChangelogError (not a bare CalledProcessError) so main() can report a
    diagnostic in this script's own voice."""
    proc = subprocess.run(
        ["git", *args], cwd=ROOT, capture_output=True, text=True
    )
    if proc.returncode != 0:
        raise ChangelogError(
            f"git {' '.join(args)} failed: {proc.stderr.strip()}"
        )
    return proc.stdout


def version_boundaries():
    """Return every commit that changed plugin-src/plugin.json's version
    field, oldest first, as {"version", "commit", "date"} dicts. A version's
    section runs from just after the previous entry's commit through this
    one, inclusive -- so the list itself carries all the range math the
    rest of the script needs."""
    log = _git(
        [
            "log",
            "--follow",
            "--reverse",
            "--format=%H %ad",
            "--date=short",
            "--",
            PLUGIN_MANIFEST_REL,
        ]
    )
    boundaries = []
    prev_version = None
    for line in log.splitlines():
        if not line.strip():
            continue
        commit_hash, date = line.split(" ", 1)
        try:
            blob = _git(["show", f"{commit_hash}:{PLUGIN_MANIFEST_REL}"])
        except ChangelogError:
            continue  # file didn't exist at this revision (e.g. a rename mid-flight)
        try:
            version = json.loads(blob).get("version")
        except json.JSONDecodeError:
            continue
        if version and version != prev_version:
            boundaries.append({"version": version, "commit": commit_hash, "date": date})
            prev_version = version
    return boundaries


def _find_boundary(boundaries, version):
    """Return (index, boundary) for VERSION, or None if no commit ever
    bumped plugin.json to it."""
    for i, boundary in enumerate(boundaries):
        if boundary["version"] == version:
            return i, boundary
    return None


def _working_tree_version():
    """Read the version straight off the working-tree manifest (not `git
    show`, which only knows committed history) -- the in-flight case is
    defined by a bump that hasn't been committed yet, so this is the only
    place that can see it."""
    path = os.path.join(ROOT, PLUGIN_MANIFEST_REL)
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f).get("version")
    except (OSError, json.JSONDecodeError):
        return None


def _commits_in_range(prev_commit, upto):
    """Return [(short_hash, subject), ...], oldest first, for every commit
    strictly after prev_commit up to and including UPTO (a commit-ish: a
    boundary commit for a released version, or "HEAD" for the in-flight
    one). When prev_commit is None (VERSION is the very first version this
    repo ever had), the range is UPTO's full ancestry."""
    rangespec = f"{prev_commit}..{upto}" if prev_commit else upto
    log = _git(["log", "--reverse", "--format=%h %s", rangespec])
    commits = []
    for line in log.splitlines():
        if not line.strip():
            continue
        short_hash, subject = line.split(" ", 1)
        commits.append((short_hash, subject))
    return commits


def _classify(subject):
    """Split a commit subject into its changelog group, optional scope, and
    the subject with any conventional-commit prefix stripped. A subject
    matching `type(scope): rest` always sheds its prefix, even when `type`
    isn't one of the four named groups -- "no raw type(scope): prefix
    surviving" applies to the Other catch-all too, not just the headline
    groups. A subject with no conventional prefix at all is untouched."""
    m = _TYPE_RE.match(subject)
    if not m:
        return "Other", None, subject
    type_, scope, rest = m.group(1), m.group(2), m.group(3)
    return _KNOWN_TYPES.get(type_, "Other"), scope, rest


def _repo_web_url():
    """Derive the repo's https base URL from its origin remote, normalizing
    the SSH form (`git@host:owner/repo.git`) to https -- GitHub renders an
    SSH-form URL as plain text, not a link, so commit links need the https
    form regardless of how this checkout was cloned."""
    url = _git(["remote", "get-url", "origin"]).strip()
    m = re.match(r"^git@([^:]+):(.+?)(?:\.git)?$", url)
    if m:
        return f"https://{m.group(1)}/{m.group(2)}"
    if url.startswith(("https://", "http://")):
        return url[:-4] if url.endswith(".git") else url
    raise ChangelogError(f"origin remote URL not recognized: {url!r}")


def render_section(version, date, commits, repo_url):
    """Render one `## VERSION` section: type prefixes unwrap into group
    headings, each entry bolds its scope (omitted when the commit had none)
    and links its short hash to the commit -- subjects are otherwise
    verbatim, since the script writes no prose of its own."""
    lines = [f"## {version} — {date}"]
    for name in _GROUP_ORDER:
        entries = []
        for short_hash, subject in commits:
            group, scope, rest = _classify(subject)
            if group == name:
                entries.append((short_hash, scope, rest))
        if not entries:
            continue
        lines.append("")
        lines.append(f"### {name}")
        for short_hash, scope, rest in entries:
            link = f"([{short_hash}]({repo_url}/commit/{short_hash}))"
            if scope:
                lines.append(f"- **{scope}:** {rest} {link}")
            else:
                lines.append(f"- {rest} {link}")
    return "\n".join(lines) + "\n"


def _split_header_and_body(text):
    """Split CHANGELOG.md into its leading header prose and the concatenated
    `## ...` sections that follow, so a prepend only has to touch the seam
    between the two rather than reparse every existing section."""
    lines = text.splitlines(keepends=True)
    for i, line in enumerate(lines):
        if line.startswith("## "):
            return "".join(lines[:i]), "".join(lines[i:])
    return text, ""


def _has_section(body, version):
    return re.search(rf"(?m)^## {re.escape(version)}\b", body) is not None


def _find_section(text, version):
    """Return VERSION's full section (heading line through the char before
    the next `## ` heading, or EOF), or None if it isn't there."""
    pattern = re.compile(rf"(?ms)^(## {re.escape(version)}\b.*?)(?=^## |\Z)")
    m = pattern.search(text)
    if not m:
        return None
    return m.group(1).rstrip("\n") + "\n"


def _remove_section(body, version):
    """Strip VERSION's section out of BODY entirely -- the in-flight refresh
    path's write half: pull the stale provisional section before the fresh
    one gets prepended, so a rerun replaces rather than duplicates."""
    pattern = re.compile(rf"(?ms)^## {re.escape(version)}\b.*?(?=^## |\Z)")
    return pattern.sub("", body, count=1)


def cmd_generate(version):
    boundaries = version_boundaries()
    match = _find_boundary(boundaries, version)
    working_version = _working_tree_version()

    in_flight = False
    if match is not None:
        # A released version: the boundary commit already exists in history,
        # so the range and its date are exactly what that commit recorded.
        idx, boundary = match
        prev_commit = boundaries[idx - 1]["commit"] if idx > 0 else None
        commits = _commits_in_range(prev_commit, boundary["commit"])
        date = boundary["date"]
    elif working_version == version:
        # In-flight: the manifest already reads VERSION in the working tree,
        # but nothing has committed that bump yet. Cover every commit since
        # the last release through HEAD, dated today -- there's no boundary
        # commit yet to date it by, and none of those commits include the
        # release commit itself, since it doesn't exist.
        prev_commit = boundaries[-1]["commit"] if boundaries else None
        commits = _commits_in_range(prev_commit, "HEAD")
        date = datetime.date.today().isoformat()
        in_flight = True
    else:
        raise ChangelogError(
            f"{version} is not a released version in "
            f"{PLUGIN_MANIFEST_REL}'s history, and the working tree is at "
            f"{working_version or 'an unreadable version'} -- bump "
            f"plugin.json to {version} before generating its section"
        )

    existing = ""
    if os.path.isfile(CHANGELOG_PATH):
        with open(CHANGELOG_PATH, encoding="utf-8") as f:
            existing = f.read()
    header, body = _split_header_and_body(existing) if existing else (HEADER, "")

    had_section = _has_section(body, version)
    if had_section:
        if not in_flight:
            raise ChangelogError(
                f"CHANGELOG.md already has a section for {version} -- "
                f"refusing to duplicate it; history is immutable for a "
                f"released version"
            )
        # In-flight refresh: more commits may have landed since the last
        # provisional run -- drop the stale section so the fresh one takes
        # its place instead of stacking a second `## VERSION` heading.
        body = _remove_section(body, version)

    repo_url = _repo_web_url()
    section = render_section(version, date, commits, repo_url)
    pieces = [header.rstrip("\n"), section.rstrip("\n")]
    if body.strip():
        pieces.append(body.rstrip("\n"))
    new_content = "\n\n".join(pieces) + "\n"

    with open(CHANGELOG_PATH, "w", encoding="utf-8") as f:
        f.write(new_content)

    if in_flight:
        verb = "refreshed the provisional" if had_section else "generated the in-flight"
        print(f"OK: {verb} {version} section in CHANGELOG.md ({len(commits)} commit(s))")
    else:
        print(f"OK: prepended the {version} section to CHANGELOG.md ({len(commits)} commit(s))")
    return 0


def cmd_notes(version):
    text = ""
    if os.path.isfile(CHANGELOG_PATH):
        with open(CHANGELOG_PATH, encoding="utf-8") as f:
            text = f.read()
    section = _find_section(text, version) if text else None
    if section is None:
        sys.stderr.write(
            f"make-changelog.py --notes: CHANGELOG.md has no section for "
            f"{version} -- run `python3 scripts/make-changelog.py {version}` "
            f"first; a release cannot ship noteless\n"
        )
        return 1
    sys.stdout.write(section)
    return 0


def main():
    parser = argparse.ArgumentParser(
        prog="make-changelog.py",
        description=(
            "Generate CHANGELOG.md sections from commit history.\n\n"
            "Modes:\n"
            "  make-changelog.py VERSION      prepend/refresh VERSION's section\n"
            "  make-changelog.py --notes VER  print VERSION's section to stdout,\n"
            "                                 or exit nonzero if it's missing"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("version", nargs="?", metavar="VERSION", help="version to generate, e.g. 0.3.6")
    parser.add_argument(
        "--notes",
        metavar="VERSION",
        help="print the existing section for VERSION instead of generating one",
    )
    args = parser.parse_args()

    if bool(args.version) == bool(args.notes):
        parser.error("give exactly one of VERSION or --notes VERSION")

    try:
        if args.notes:
            return cmd_notes(args.notes)
        return cmd_generate(args.version)
    except ChangelogError as e:
        sys.stderr.write(f"make-changelog.py: {e}\n")
        return 1


if __name__ == "__main__":
    sys.exit(main())
